// <auto-generated />
namespace Blog.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addStatusOnPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addStatusOnPost));
        
        string IMigrationMetadata.Id
        {
            get { return "202205291434442_addStatusOnPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
