// <auto-generated />
namespace KutuphaneYonetimi2O.Entites.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addPersonelFotograf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPersonelFotograf));
        
        string IMigrationMetadata.Id
        {
            get { return "202111161451100_addPersonelFotograf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
