// <auto-generated />
namespace KutuphaneYonetimi1O.Entites.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class githubRepositoryDegisimiDatabaseCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(githubRepositoryDegisimiDatabaseCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202110261416550_githubRepositoryDegisimiDatabaseCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
